
GRANT ALL PRIVILEGES ON DATABASE elmo TO elmo_svc;
GRANT ALL PRIVILEGES ON SCHEMA oscar TO elmo_svc;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO elmo_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA oscar TO elmo_svc;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO elmo_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA oscar GRANT ALL PRIVILEGES ON TABLES TO elmo_svc;